/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/BlackBN/KubenetesDemo/database-controller/pkg/apis/databasemanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatabaseManagers implements DatabaseManagerInterface
type FakeDatabaseManagers struct {
	Fake *FakeCoolopsV1alpha1
	ns   string
}

var databasemanagersResource = schema.GroupVersionResource{Group: "coolops.cn", Version: "v1alpha1", Resource: "databasemanagers"}

var databasemanagersKind = schema.GroupVersionKind{Group: "coolops.cn", Version: "v1alpha1", Kind: "DatabaseManager"}

// Get takes name of the databaseManager, and returns the corresponding databaseManager object, and an error if there is any.
func (c *FakeDatabaseManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatabaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(databasemanagersResource, c.ns, name), &v1alpha1.DatabaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseManager), err
}

// List takes label and field selectors, and returns the list of DatabaseManagers that match those selectors.
func (c *FakeDatabaseManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatabaseManagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(databasemanagersResource, databasemanagersKind, c.ns, opts), &v1alpha1.DatabaseManagerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DatabaseManagerList{ListMeta: obj.(*v1alpha1.DatabaseManagerList).ListMeta}
	for _, item := range obj.(*v1alpha1.DatabaseManagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested databaseManagers.
func (c *FakeDatabaseManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(databasemanagersResource, c.ns, opts))

}

// Create takes the representation of a databaseManager and creates it.  Returns the server's representation of the databaseManager, and an error, if there is any.
func (c *FakeDatabaseManagers) Create(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.CreateOptions) (result *v1alpha1.DatabaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(databasemanagersResource, c.ns, databaseManager), &v1alpha1.DatabaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseManager), err
}

// Update takes the representation of a databaseManager and updates it. Returns the server's representation of the databaseManager, and an error, if there is any.
func (c *FakeDatabaseManagers) Update(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (result *v1alpha1.DatabaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(databasemanagersResource, c.ns, databaseManager), &v1alpha1.DatabaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseManager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDatabaseManagers) UpdateStatus(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (*v1alpha1.DatabaseManager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(databasemanagersResource, "status", c.ns, databaseManager), &v1alpha1.DatabaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseManager), err
}

// Delete takes name of the databaseManager and deletes it. Returns an error if one occurs.
func (c *FakeDatabaseManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(databasemanagersResource, c.ns, name, opts), &v1alpha1.DatabaseManager{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatabaseManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(databasemanagersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DatabaseManagerList{})
	return err
}

// Patch applies the patch and returns the patched databaseManager.
func (c *FakeDatabaseManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(databasemanagersResource, c.ns, name, pt, data, subresources...), &v1alpha1.DatabaseManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseManager), err
}
