apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databasemanagers.coolops.cn
spec:
  group: coolops.cn
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                dbtype:
                  type: string
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
  names:
    kind: DatabaseManager
    plural: databasemanagers
    singular: databasemanager
    shortNames:
      - dm
  scope: Namespaced