---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.bnblak.com
  resources:
  - stsinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.bnblak.com
  resources:
  - stsinstalls/finalizers
  verbs:
  - update
- apiGroups:
  - demo.bnblak.com
  resources:
  - stsinstalls/status
  verbs:
  - get
  - patch
  - update
