/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	versioned "github.com/BlackBN/KubenetesDemo/database-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/BlackBN/KubenetesDemo/database-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/BlackBN/KubenetesDemo/database-controller/pkg/client/listers/databasemanager/v1alpha1"
	time "time"

	databasemanagerv1alpha1 "github.com/BlackBN/KubenetesDemo/database-controller/pkg/apis/databasemanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatabaseManagerInformer provides access to a shared informer and lister for
// DatabaseManagers.
type DatabaseManagerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DatabaseManagerLister
}

type databaseManagerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatabaseManagerInformer constructs a new informer for DatabaseManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatabaseManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatabaseManagerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatabaseManagerInformer constructs a new informer for DatabaseManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatabaseManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoolopsV1alpha1().DatabaseManagers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoolopsV1alpha1().DatabaseManagers(namespace).Watch(context.TODO(), options)
			},
		},
		&databasemanagerv1alpha1.DatabaseManager{},
		resyncPeriod,
		indexers,
	)
}

func (f *databaseManagerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatabaseManagerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *databaseManagerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&databasemanagerv1alpha1.DatabaseManager{}, f.defaultInformer)
}

func (f *databaseManagerInformer) Lister() v1alpha1.DatabaseManagerLister {
	return v1alpha1.NewDatabaseManagerLister(f.Informer().GetIndexer())
}
