
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: admission-registry
    app.kubernetes.io/name: admission-registry
  name: admission-registry
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW55Z0F3SUJBZ0lVVzJ1Wkd1VlAyNU5pb2RnNFVQamxjeGpxV1Jrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZDZhRzkxTVJFd0R3WURWUVFIRXdoSQpZVzVuZW1odmRURVBNQTBHQTFVRUNoTUdRbTVpYkdGck1RMHdDd1lEVlFRTEV3UlRaV3htTVEwd0N3WURWUVFECkV3UnliMjkwTUI0WERUSTFNRFl3T0RFd01Ea3dNRm9YRFRJMk1EWXdPREV3TURrd01Gb3dZakVMTUFrR0ExVUUKQmhNQ1EwNHhFVEFQQmdOVkJBZ1RDRWhoYm1kNmFHOTFNUkV3RHdZRFZRUUhFd2hJWVc1bmVtaHZkVEVQTUEwRwpBMVVFQ2hNR1FtNWliR0ZyTVEwd0N3WURWUVFMRXdSVFpXeG1NUTB3Q3dZRFZRUURFd1J5YjI5ME1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVrWkVQS3pySkRtZkhLb05pRXI1a3NuSWZUZzAKL1ZldFNhdGxTWXd3SGp3emNuTnE5UUgzdFBWakFmMk5kSG9QSTl1dDAxRVIzc1Z3NkRTdEoyWE1ac0NGcXhqMQpqcklCMUFpaG5vU3M4dHh6MHRRWjBnclRHVWVPMGcwUGp2a0NwRU9ZZUlnREo0RkhnNTd1dWV1SnZJMjhlUXNCClZuKzlTUWlZT3lSMHZlMlhMc3NyVmovRDhNcmtrYU81MkFVL1U0YTg1VXZHNi9FWkZGYjNEdURNRFFRUnU0RU4KK0YrUHhNWU9hWlNpV21RRHQvTDNFWVlDVENNbkd1b2hmS1hpZUFCcFFCanlSaUFpL3crWEczWFViWHRVVE84UQpTQTJGTWJRQVcrMEJqSWNORlNEVXdOWVM2dXR0bldQeU85YWJyOXdCcjBKOFByNUpOMGZGUXlzWHFRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKdnd1T20vNElmUWloWDV5eDNKYXNEWGxpSHFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFM2dUcUlDdUk3SgpESjJYSEM1UXJJaVZ6V1lIYWxMQjREQXg2VXNyemJTV1N3QW1XN283b0xtdlllSDhxZXZxYlFXWkpqNUZNcmJpClhzK0dVcmh0Nk1kdzBxcFRodjJOTmF5Mld1cENKYkh4UmQyYldzdC9DYlRKLzBFWEh6Y0VqSkNEUWIzVVNld0EKUWhkZDJWbm45MmdjRXVRemVQMU5ERGw5aTdISG1aRGxEMU4xcTg3WVR1WTlSNUFXYkRBeUY3K1JaLzNsNEFJVwpxSnF3Qzd5K3p2MVd4REx6UFlhSUNTYVVZVTc2Ull1U1Z5KzVMUFdZdGltQ0VWZ2lSSEQ1d3NxcFVRNHRqWkxwCkJsVzc0V2taOEl4eU1pSmxmVnBuUGlqeHRmenllcmh6YklsSy9JeG9LZEdpWEFSMzVXVjhlc1VZVnFrQWRtZ0oKYkdaQ3d3ejhvaTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: admission-registry
      namespace: waf
      path: /validate
      port: 443
  name: bnblak.com.admissiono-registry
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE","UPDATE"]
    resources: ["pods"]
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: admission-registry
    app.kubernetes.io/name: admission-registry
  name: admission-registry
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW55Z0F3SUJBZ0lVVzJ1Wkd1VlAyNU5pb2RnNFVQamxjeGpxV1Jrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZDZhRzkxTVJFd0R3WURWUVFIRXdoSQpZVzVuZW1odmRURVBNQTBHQTFVRUNoTUdRbTVpYkdGck1RMHdDd1lEVlFRTEV3UlRaV3htTVEwd0N3WURWUVFECkV3UnliMjkwTUI0WERUSTFNRFl3T0RFd01Ea3dNRm9YRFRJMk1EWXdPREV3TURrd01Gb3dZakVMTUFrR0ExVUUKQmhNQ1EwNHhFVEFQQmdOVkJBZ1RDRWhoYm1kNmFHOTFNUkV3RHdZRFZRUUhFd2hJWVc1bmVtaHZkVEVQTUEwRwpBMVVFQ2hNR1FtNWliR0ZyTVEwd0N3WURWUVFMRXdSVFpXeG1NUTB3Q3dZRFZRUURFd1J5YjI5ME1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVrWkVQS3pySkRtZkhLb05pRXI1a3NuSWZUZzAKL1ZldFNhdGxTWXd3SGp3emNuTnE5UUgzdFBWakFmMk5kSG9QSTl1dDAxRVIzc1Z3NkRTdEoyWE1ac0NGcXhqMQpqcklCMUFpaG5vU3M4dHh6MHRRWjBnclRHVWVPMGcwUGp2a0NwRU9ZZUlnREo0RkhnNTd1dWV1SnZJMjhlUXNCClZuKzlTUWlZT3lSMHZlMlhMc3NyVmovRDhNcmtrYU81MkFVL1U0YTg1VXZHNi9FWkZGYjNEdURNRFFRUnU0RU4KK0YrUHhNWU9hWlNpV21RRHQvTDNFWVlDVENNbkd1b2hmS1hpZUFCcFFCanlSaUFpL3crWEczWFViWHRVVE84UQpTQTJGTWJRQVcrMEJqSWNORlNEVXdOWVM2dXR0bldQeU85YWJyOXdCcjBKOFByNUpOMGZGUXlzWHFRSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKdnd1T20vNElmUWloWDV5eDNKYXNEWGxpSHFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFM2dUcUlDdUk3SgpESjJYSEM1UXJJaVZ6V1lIYWxMQjREQXg2VXNyemJTV1N3QW1XN283b0xtdlllSDhxZXZxYlFXWkpqNUZNcmJpClhzK0dVcmh0Nk1kdzBxcFRodjJOTmF5Mld1cENKYkh4UmQyYldzdC9DYlRKLzBFWEh6Y0VqSkNEUWIzVVNld0EKUWhkZDJWbm45MmdjRXVRemVQMU5ERGw5aTdISG1aRGxEMU4xcTg3WVR1WTlSNUFXYkRBeUY3K1JaLzNsNEFJVwpxSnF3Qzd5K3p2MVd4REx6UFlhSUNTYVVZVTc2Ull1U1Z5KzVMUFdZdGltQ0VWZ2lSSEQ1d3NxcFVRNHRqWkxwCkJsVzc0V2taOEl4eU1pSmxmVnBuUGlqeHRmenllcmh6YklsSy9JeG9LZEdpWEFSMzVXVjhlc1VZVnFrQWRtZ0oKYkdaQ3d3ejhvaTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: admission-registry
      namespace: waf
      path: /mutate
      port: 443
  name: bnblak.com.admissiono-registry
  rules:
  - apiGroups: ["apps",""]
    apiVersions: ["v1"]
    operations: ["CREATE","UPDATE"]
    resources: ["deployments","services"]
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
