/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	scheme "github.com/BlackBN/KubenetesDemo/database-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1alpha1 "github.com/BlackBN/KubenetesDemo/database-controller/pkg/apis/databasemanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatabaseManagersGetter has a method to return a DatabaseManagerInterface.
// A group's client should implement this interface.
type DatabaseManagersGetter interface {
	DatabaseManagers(namespace string) DatabaseManagerInterface
}

// DatabaseManagerInterface has methods to work with DatabaseManager resources.
type DatabaseManagerInterface interface {
	Create(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.CreateOptions) (*v1alpha1.DatabaseManager, error)
	Update(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (*v1alpha1.DatabaseManager, error)
	UpdateStatus(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (*v1alpha1.DatabaseManager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DatabaseManager, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DatabaseManagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseManager, err error)
	DatabaseManagerExpansion
}

// databaseManagers implements DatabaseManagerInterface
type databaseManagers struct {
	client rest.Interface
	ns     string
}

// newDatabaseManagers returns a DatabaseManagers
func newDatabaseManagers(c *CoolopsV1alpha1Client, namespace string) *databaseManagers {
	return &databaseManagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseManager, and returns the corresponding databaseManager object, and an error if there is any.
func (c *databaseManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatabaseManager, err error) {
	result = &v1alpha1.DatabaseManager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasemanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseManagers that match those selectors.
func (c *databaseManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatabaseManagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatabaseManagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseManagers.
func (c *databaseManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databasemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a databaseManager and creates it.  Returns the server's representation of the databaseManager, and an error, if there is any.
func (c *databaseManagers) Create(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.CreateOptions) (result *v1alpha1.DatabaseManager, err error) {
	result = &v1alpha1.DatabaseManager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databasemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseManager).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a databaseManager and updates it. Returns the server's representation of the databaseManager, and an error, if there is any.
func (c *databaseManagers) Update(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (result *v1alpha1.DatabaseManager, err error) {
	result = &v1alpha1.DatabaseManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasemanagers").
		Name(databaseManager.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseManager).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *databaseManagers) UpdateStatus(ctx context.Context, databaseManager *v1alpha1.DatabaseManager, opts v1.UpdateOptions) (result *v1alpha1.DatabaseManager, err error) {
	result = &v1alpha1.DatabaseManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasemanagers").
		Name(databaseManager.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseManager).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the databaseManager and deletes it. Returns an error if one occurs.
func (c *databaseManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasemanagers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasemanagers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched databaseManager.
func (c *databaseManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseManager, err error) {
	result = &v1alpha1.DatabaseManager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databasemanagers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
